/// Flutter icons CustomIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';
  static const _kFontPkg = null;

  static const IconData card_account_details_outline = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_outline = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash_usd_outline = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog_outline = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_menu_outline = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData format_list_checkbox = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData numeric_9_plus_circle_outline = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag_text_outline = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_outline = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket_outline = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_text = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circle_outline = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_check_outline = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
